import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import { ChakraProvider,GridItem,Grid,Button, Card, CardHeader, CardBody, CardFooter,Text,Heading,Stack,StackDivider,Box ,SimpleGrid  ,Container} from '@chakra-ui/react'

export default function thankyou() {
    return (
      <>
        <Head>
          <title>Surat Digital</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          
        </Head>
        Container
        <main className={styles.main}>
       
        </main>
      </>
    )
    
  }
  